version: "3"

networks:
  booking-net:

services:
  booking:
    image: helloalf/microservice-booking
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - booking-net

  mongo:
    image: mongo:4.4.4
    environment:
      - MONGO_INITDB_DATABASE=nestjs_mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27018:27017"
    networks:
      - booking-net
    volumes:
      - ./mongo_data:/data/db
